name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PLATFORMS: |
    linux/amd64
  TAGS: |
    type=raw,value=latest,enable={{is_default_branch}}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Login to Docker Hub
        if: ${{ github.actor == github.repository_owner }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Collect image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: ${{ env.TAGS }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.actor == github.repository_owner }}
          load: ${{ github.actor != github.repository_owner }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: release
          cache-from: |
            ${{ github.repository }}-cache
          cache-to: |
            type=registry,ref=${{ github.repository }}-cache,mode=max
          platforms: ${{ env.PLATFORMS }}
